client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /client

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


client_login_check:
    pattern: /client/login/check
    
client_logout:
   pattern: /client/logout